// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyzsgtigwezgglagvbou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5enNndGlnd2V6Z2dsYWd2Ym91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTE3MjEsImV4cCI6MjA2NDEyNzcyMX0.6gNIiDVTaCMhw2dolXebUvZ-9146olJIaIGiPY-gVuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);